name: daily-build

on:
  schedule:
    - cron: "7 10 * * *"   # daily at 10:07 UTC
  workflow_dispatch:
  push:                     # run on small edits to these paths
    branches: [main]
    paths:
      - 'layer1/**'
      - 'layer2/**'
      - 'layer3/**'
      - 'scripts/**'
      - 'data/**'
      - 'blog/**'
      - 'feeds/**'
      - 'config/**'
      - 'package.json'
      - '.github/workflows/daily.yaml'

# grant GITHUB_TOKEN write where allowed
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HAS_PAT: ${{ secrets.ACTIONS_TOKEN || '' }}   # optional PAT (classic) with repo scope
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (Node)
        run: npm ci || npm install

      # 🔁 Your pipeline — adjust if your paths differ
      - name: Snap targets
        run: node scripts/snap.js layer1/targets.txt layer1/snaps

      - name: Fetch JSON
        run: node scripts/fetch_json.js

      - name: Build blog & feeds
        run: python3 scripts/build_lottery_blog.py

      # ✅ Sanity check: fail loudly if data is missing/empty
      - name: Verify dataset exists and is non-empty
        run: |
          set -e
          test -s data/latest.json
          python3 - <<'PY'
          import json,sys
          with open('data/latest.json','r') as f:
              d=json.load(f)
          if not isinstance(d,dict) or not d.get('records'):
              sys.exit("latest.json missing 'records' or empty")
          print("latest.json OK —", len(d['records']), "records")
          PY

      # 🧠 Commit using GITHUB_TOKEN when org allows write
      - name: Commit & push (GITHUB_TOKEN)
        if: env.HAS_PAT == ''    # only if no PAT provided
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto: publish datasets & blog ($(date -u +'%Y-%m-%d'))"
          branch: main
          push_options: --force-with-lease

      # 🔐 Commit & push using PAT fallback (bypasses read-only token policy)
      - name: Commit changes (manual)
        if: env.HAS_PAT != ''    # only if PAT provided
        run: |
          git config user.name "HypnoData Bot"
          git config user.email "bot@hypnodatalabs"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 0
          fi
          git commit -m "Auto: publish datasets & blog ($(date -u +'%Y-%m-%d'))"

      - name: Push (PAT)
        if: env.HAS_PAT != ''    # only if PAT provided
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          branch: main

  # 📧 Optional failure email (only runs if SMTP secrets exist)
  notify-on-failure:
    needs: build
    if: failure() && env.HAS_SMTP != ''
    runs-on: ubuntu-latest
    env:
      HAS_SMTP: ${{ secrets.SMTP_SERVER || '' }}
    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Daily build FAILED: whatwouldyoudoifyouwonthelottery"
          from: ${{ secrets.FROM_EMAIL }}
          to: ${{ secrets.TO_EMAIL }}
          secure: true
          ignore_cert: false
          priority: high
          body: |
            Daily build failed for whatwouldyoudoifyouwonthelottery.

            Repo: ${{ github.repository }}
            Run:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Ref:  ${{ github.ref }}

            Please check the Actions logs.
